In [1]:
import math
import random
import numpy as np

x_train = np.zeros((60000,3))
y_train = np.zeros(60000)

x_test = np.zeros((10000,3))
y_test = np.zeros(10000)

action = 0

for i in range(70000):
    j = random.randint(1,52)
    handscore = random.randint(0, 500)
    random.seed(j)
    opptscore = random.randint(0,500)
    random.seed(j+1)
    
    w2 = random.random()

    opptscore = opptscore * w2

    gamescore = handscore + opptscore

    if gamescore<200:
      action = 0 #fold/check
    elif gamescore<500:
      action = 1 #call/check
    else:
      action = 2 #bet
    if i<10000:
      x_test[i][0] = handscore
      x_test[i][1] = opptscore
      x_test[i][2] = action
      y_test[i] = action
    else:
      x_train[i-10000][0] = handscore
      x_train[i-10000][1] = opptscore
      x_train[i-10000][2] = action
      y_train[i-10000] = action    

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Activation
from keras.layers import Dropout

In [ ]:
model = Sequential()
model.add(LSTM(3,input_shape=(3,1),return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(100,kernel_initializer='normal', activation='relu'))
model.add(Dense(3,kernel_initializer='normal',activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer ='adam',metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=20,batch_size=60,validation_split=0.05,verbose=1)

Epoch 1/20
950/950 [==============================] - 7s 5ms/step - loss: 0.3093 - accuracy: 0.8530 - val_loss: 2.4771e-04 - val_accuracy: 1.0000
Epoch 2/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0809 - accuracy: 0.9581 - val_loss: 2.1537e-05 - val_accuracy: 1.0000
Epoch 3/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0801 - accuracy: 0.9585 - val_loss: 7.1923e-06 - val_accuracy: 1.0000
Epoch 4/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0799 - accuracy: 0.9579 - val_loss: 1.6689e-06 - val_accuracy: 1.0000
Epoch 5/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0796 - accuracy: 0.9591 - val_loss: 4.3710e-07 - val_accuracy: 1.0000
Epoch 6/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0792 - accuracy: 0.9591 - val_loss: 1.5895e-07 - val_accuracy: 1.0000
Epoch 7/20
950/950 [==============================] - 4s 4ms/step - loss: 0.0802 - accuracy: 0.9586 - val_loss: 7.9473e-08 -

In [ ]:
scores = model.evaluate(x_test, y_test, verbose=1, batch_size=5)

2000/2000 [==============================] - 6s 3ms/step - loss: 0.0000e+00 - accuracy: 1.0000


In [ ]:
import matplotlib.pyplot as plt

predict = model.predict(x_test)
print(y_test)

313/313 [==============================] - 1s 2ms/step
[1. 2. 2. ... 2. 2. 1.]


In [ ]:
print(predict)

[[4.3458773e-21 1.0000000e+00 8.0555285e-12]
 [1.7420832e-20 6.4490677e-11 1.0000000e+00]
 [1.5412116e-20 6.0675666e-11 1.0000000e+00]
 ...
 [1.7420832e-20 6.4490802e-11 1.0000000e+00]
 [1.5412116e-20 6.0675666e-11 1.0000000e+00]
 [4.3459100e-21 1.0000000e+00 8.0555597e-12]]
